# Generated by Django 4.1.9 on 2023-05-07 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("create", models.DateTimeField(auto_now_add=True)),
                ("update", models.DateTimeField(auto_now_add=True)),
                ("contents", models.TextField(max_length=500)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="answer_question", to="curation.question"
            ),
        ),
        migrations.DeleteModel(
            name="Qna",
        ),
    ]
