# Generated by Django 4.1.9 on 2023-05-08 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0002_question_alter_answer_question_delete_qna"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("create", models.DateTimeField(auto_now_add=True)),
                ("update", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=200, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="answer",
            name="a1",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="a2",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="a3",
        ),
        migrations.RemoveField(
            model_name="question",
            name="contents",
        ),
        migrations.AddField(
            model_name="answer",
            name="answer_text",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="question_text",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="curation.question"),
        ),
        migrations.AddField(
            model_name="answer",
            name="category",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="curation.category"),
        ),
    ]
