# Generated by Django 4.1.9 on 2023-05-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0006_alter_result_youtube"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="vaule",
            field=models.IntegerField(null=True),
        ),
    ]
