# Generated by Django 4.1.9 on 2023-05-17 11:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0009_rename_vaule_answer_value"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={"ordering": ["id"]},
        ),
    ]
