# Generated by Django 4.1.9 on 2023-05-18 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0010_alter_answer_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("create", models.DateTimeField(auto_now_add=True)),
                ("update", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=200, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameModel(
            old_name="Category",
            new_name="AnswerCategory",
        ),
        migrations.AddField(
            model_name="question",
            name="question_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="curation.questioncategory"
            ),
        ),
    ]
