# Generated by Django 4.1.9 on 2023-05-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0011_questioncategory_rename_category_answercategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="q_index",
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
