# Generated by Django 4.1.9 on 2023-05-24 03:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0012_question_q_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="q_index",
        ),
    ]
