# Generated by Django 4.1.9 on 2023-05-25 00:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0014_question_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="user",
        ),
    ]
