# Generated by Django 4.1.9 on 2023-05-25 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0017_questionindex"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionindex",
            name="question",
        ),
        migrations.AddField(
            model_name="question",
            name="question_index",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="index_q",
                to="curation.questionindex",
            ),
        ),
    ]
