# Generated by Django 4.1.9 on 2023-05-25 03:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0018_remove_questionindex_question_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="question_category",
        ),
    ]
