# Generated by Django 4.1.9 on 2023-05-25 05:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0020_answer_question_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="question_index",
        ),
    ]
