# Generated by Django 4.1.9 on 2023-05-25 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0021_remove_answer_question_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="question_index",
        ),
        migrations.RemoveField(
            model_name="question",
            name="user",
        ),
        migrations.AddField(
            model_name="question",
            name="question_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="curation.questioncategory"
            ),
        ),
        migrations.DeleteModel(
            name="QuestionIndex",
        ),
    ]
