# Generated by Django 4.1.9 on 2023-05-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0022_remove_question_question_index_remove_question_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_title",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
