# Generated by Django 4.1.9 on 2023-05-21 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("userType", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=255, null=True, verbose_name="Name of User"),
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="users.usertype"),
        ),
    ]
