# Generated by Django 4.1.9 on 2023-05-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_first_name_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=255, null=True, verbose_name="닉네임"),
        ),
    ]
